#!/usr/bin/env python

import SimpleHTTPServer
import SocketServer
import logging

PORT = 80

class GetHandlerTest(SimpleHTTPServer.SimpleHTTPRequestHandler):

    def do_GET(self):
        logging.error(self.headers)
        SimpleHTTPServer.SimpleHTTPRequestHandler.do_GET(self)


Handler = GetHandlerTest
httpd = SocketServer.TCPServer(("", PORT), Handler)

httpd.serve_forever()
